version: "3.8"

networks:
  merchant_net:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - ENVIRONMENT=prod
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/merchant_leads
      - REDIS_URL=redis://redis:6379/0
    restart: always
    networks:
      - merchant_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      bash -c "alembic upgrade head && 
              uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=merchant_leads
    ports:
      - "5432:5432"
    networks:
      - merchant_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - merchant_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    networks:
      - merchant_net
    depends_on:
      - backend
    container_name: cardiff_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    stdin_open: true
    tty: true
    restart: always

volumes:
  postgres_data:
  redis_data:
